/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SearchCriteria } from "./SearchCriteria";
import { SearchCriteriaCountArgs } from "./SearchCriteriaCountArgs";
import { SearchCriteriaFindManyArgs } from "./SearchCriteriaFindManyArgs";
import { SearchCriteriaFindUniqueArgs } from "./SearchCriteriaFindUniqueArgs";
import { DeleteSearchCriteriaArgs } from "./DeleteSearchCriteriaArgs";
import { SearchCriteriaService } from "../searchCriteria.service";
@graphql.Resolver(() => SearchCriteria)
export class SearchCriteriaResolverBase {
  constructor(protected readonly service: SearchCriteriaService) {}

  async _searchCriteriaItemsMeta(
    @graphql.Args() args: SearchCriteriaCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SearchCriteria])
  async searchCriteriaItems(
    @graphql.Args() args: SearchCriteriaFindManyArgs
  ): Promise<SearchCriteria[]> {
    return this.service.searchCriteriaItems(args);
  }

  @graphql.Query(() => SearchCriteria, { nullable: true })
  async searchCriteria(
    @graphql.Args() args: SearchCriteriaFindUniqueArgs
  ): Promise<SearchCriteria | null> {
    const result = await this.service.searchCriteria(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SearchCriteria)
  async deleteSearchCriteria(
    @graphql.Args() args: DeleteSearchCriteriaArgs
  ): Promise<SearchCriteria | null> {
    try {
      return await this.service.deleteSearchCriteria(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
